### ISSUE TITLE
Is this the official repo for pxlib?

### ISSUE THREAD

**Issue by echoix** [steinm/pxlib#4]
I wanted to know if this is the current code repository for the pxlib project found on 
https://pxlib.sourceforge.net
and
https://sourceforge.net/projects/pxlib/

The repo here doesn't have any releases nor recent tags, but seems to be containing a 0.6.8 release, that is found on https://sourceforge.net/projects/pxlib/files/pxlib/0.6.8/ but is not present on the website.

The code tab on https://sourceforge.net/p/pxlib/code/ isn't configured to show the code repo, as it is still on CVS, and the cvs repo seems to be older.

I played a little bit with the code to try to build it from source, and have some adjustments that I would want to share back.

**Comment by SeedDMS** [comment]
Yes, it is.

**Comment by echoix** [comment]
Great! Thanks!

**Comment by ryandesign** [comment]
I recommend reopening this issue until something has been done to make the situation less confusing.

The README here still refers users to the web site on SourceForge:

https://github.com/steinm/pxlib/blob/cd65ac2255a02612a9b2c25bf4f17684ab391d38/README#L12

That web site has broken links, doesn't mention the latest version, and doesn't mention the existence of this GitHub repo. 

This GitHub repo doesn't have recent tags or any releases.

The SourceForge project page doesn't mention that the project has moved to GitHub. There are links to the GitHub repo in some SourceForge tickets, but that doesn't tell me if those comments are from the developer or just some random user.

Neither SourceForge nor GitHub have tags nor distfiles for version 0.6.9 which seems to have been released in 2024 (781a234fc4114da61b26ebe7e72341fa75da2d7d).

There hasn't even been a comment in this issue from the repository owner answering the question, only a comment from some other user who is not listed as a contributor to this repository.
